<a href="https://colab.research.google.com/github/ianelgar40/IansMIS433/blob/main/Copy_of_relational_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Relational Data

In data analysis, you often need to combine multiple data sets to answer the questions that you are interested in.

Collectively, multiple related sets (tables) of data are called relational data. In relational (SQL) databases (DBs), each table is called a relation. Two tables (relations) may have a relationship between each other via a PK (primary key) and a FK (foreign key). It is also not uncommon to have more than two tables related to each other.

To work with relational data, we typically need to perform three families of operations:
- **Mutating joins**, which add new variables to one data frame from matching observations in another.
- **Filtering joins**, which filter observations from one data frame based on whether or not they match an observation in the other table.
- **Set operations**, which treat observations as if they were set elements.

If you have learned relational databases and SQL (Structured Query Language), you should find many of these concepts and operations familiar.

We will use the **nycflights13** package to learn about relational data.

In [5]:
!pip install nycflights13

Collecting nycflights13
  Downloading nycflights13-0.0.3.tar.gz (8.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.7/8.7 MB 74.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from nycflights13) (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=0.24.0->nycflights13) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=0.24.0->nycflights13) (1.17.0)
Building wheels for collected packages: nycflights13
  Building wheel for nycflights13 (setup.py) ... done
  Created wheel for nycflights13: filename=nycflights13-0.0.3-py3-none-any.whl size=8732722 sha256=96de1e97498fc02f4600622a59da923913f6911402aea4bc1a1e974e113e0dc3
  Stored in directory: /root/.cache/pip/wheels/58/ee/20/7838832df5510701439239ec10c2d8927de32aac2729ce2085
Successfully built nycflights13
Installing collected packages: nycflights13
Successfully installed nycflights13-0.0.3

In [6]:
import pandas as pd

# Install the "nycflights13" package before you run the following code.
from nycflights13 import flights
from nycflights13 import airlines
from nycflights13 import airports
from nycflights13 import planes
from nycflights13 import weather

In [7]:
flights.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T10:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z

In [8]:
airlines.head()

  carrier                    name
0      9E       Endeavor Air Inc.
1      AA  American Airlines Inc.
2      AS    Alaska Airlines Inc.
3      B6         JetBlue Airways
4      DL    Delta Air Lines Inc.

In [9]:
airports.head()

,faa,name,lat,lon,alt,tz,dst,tzone
0,04G,Lansdowne Airport,41.130472,-80.619583,1044,-5,A,America/New_York
1,06A,Moton Field Municipal Airport,32.460572,-85.680028,264,-6,A,America/Chicago
2,06C,Schaumburg Regional,41.989341,-88.101243,801,-6,A,America/Chicago
3,06N,Randall Airport,41.431912,-74.391561,523,-5,A,America/New_York
4,09J,Jekyll Island Airport,31.074472,-81.427778,11,-5,A,America/New_York

In [10]:
planes.head()

,tailnum,year,type,manufacturer,model,engines,seats,speed,engine
0,N10156,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
1,N102UW,1998.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
2,N103US,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
3,N104UW,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
4,N10575,2002.0,Fixed wing multi engine,EMBRAER,EMB-145LR,2,55,NaN,Turbo-fan

In [11]:
weather.head()

,origin,year,month,day,hour,temp,dewp,humid,wind_dir,wind_speed,wind_gust,precip,pressure,visib,time_hour
0,EWR,2013,1,1,1,39.02,26.06,59.37,270.0,10.35702,NaN,0.0,1012.0,10.0,2013-01-01T06:00:00Z
1,EWR,2013,1,1,2,39.02,26.96,61.63,250.0,8.05546,NaN,0.0,1012.3,10.0,2013-01-01T07:00:00Z
2,EWR,2013,1,1,3,39.02,28.04,64.43,240.0,11.50780,NaN,0.0,1012.5,10.0,2013-01-01T08:00:00Z
3,EWR,2013,1,1,4,39.92,28.04,62.21,250.0,12.65858,NaN,0.0,1012.2,10.0,2013-01-01T09:00:00Z
4,EWR,2013,1,1,5,39.02,28.04,64.43,260.0,12.65858,NaN,0.0,1011.9,10.0,2013-01-01T10:00:00Z

The relationships between these tables are shown in the following diagram:

In [ ]:
from IPython.display import Image
Image('https://d33wubrfki0l68.cloudfront.net/245292d1ea724f6c3fd8a92063dcd7bfb9758d02/5751b/diagrams/relational-nycflights.png')

For nycflights13:

- ``flights`` connects to ``planes`` via a single variable, ``tailnum``.
- ``flights`` connects to ``airlines`` through the ``carrier`` variable.
- ``flights`` connects to ``airports`` in two ways: via the ``origin`` and ``dest`` variables.
- ``flights`` connects to ``weather`` via origin (the location), and ``year``, ``month``, ``day`` and ``hour`` (the time).

## Keys

The variables used to connect each pair of tables are called **keys**. A key is a variable (or set of variables) that uniquely identifies an observation.

For example, each plane is uniquely identified by its ``tailnum``. In other cases, multiple variables may be needed. For example, to identify an observation in weather you need five variables: ``year``, ``month``, ``day``, ``hour``, and ``origin``.

There are two types of keys:
- A primary key uniquely identifies an observation in its own table. For example, in the ``planes`` table, ``tailnum`` is a primary key because it uniquely identifies each plane in the ``planes`` table.
- A foreign key uniquely identifies an observation in another table. For example, in the ``flights`` table, ``tailnum`` is a foreign key because it matches each flight to a unique plane.

Once you've identified the primary keys in your tables, it is good practice to verify that they do indeed uniquely identify each observation.

In [12]:
# Count the number of rows in the table "planes"
planes.shape[0]

3322

In [13]:
# Count the number of unique values in column "tailnum"
planes.tailnum.nunique()

3322

In [14]:
# Count the occurrence of different values in column "tailnum"
planes.tailnum.value_counts()

tailnum
N999DN    1
N10156    1
N102UW    1
N103US    1
N104UW    1
         ..
N11119    1
N11113    1
N11109    1
N11107    1
N11106    1
Name: count, Length: 3322, dtype: int64

In [15]:
# Try to determine the key for flights: ['year','month','day','carrier','flight']
flights[['year','month','day','carrier','flight']].value_counts()

year  month  day  carrier  flight
2013  8      15   UA       236       2
             19   UA       207       2
      6      15   WN       2269      2
      8      26   UA       207       2
             20   UA       635       2
                                    ..
      5      4    B6       553       1
                           547       1
                           537       1
                           527       1
                           625       1
Name: count, Length: 336752, dtype: int64

In [16]:
# Adding more variable(s) to make a key?
flights[['year','month','origin','day','carrier','flight']].value_counts()

year  month  origin  day  carrier  flight
2013  12     LGA     31   YV       3771      1
      1      EWR     1    AA       119       1
                                   883       1
                                   1589      1
                                   1623      1
                                            ..
                          B6       215       1
                          AS       11        1
                                   7         1
                          AA       2083      1
                                   2075      1
Name: count, Length: 336776, dtype: int64

Sometimes a table doesn’t have an explicit primary key: each row is an observation, but no combination of variables reliably identifies it.

If a table lacks a primary key or a non-composite key, it’s sometimes useful to add one, e.g., its row number. That makes it easier to match observations if you’ve done some filtering and want to check back in with the original data. This is called a **surrogate key**.

In [17]:
# Add a surrogate key to flights.
flights['id'] = flights.index
flights.head()

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour,id
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z,0
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z,1
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z,2
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,725,N804JB,JFK,BQN,183.0,1576,5,45,2013-01-01T10:00:00Z,3
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,461,N668DN,LGA,ATL,116.0,762,6,0,2013-01-01T11:00:00Z,4

## Standard Joins

Join two data sets/tables by the PK-FK relationship.

Create two datasets, ``adf`` and ``bdf``:

In [18]:
adf = pd.DataFrame(
    [['A',1],
     ['B',2],
     ['C',3]],
    columns=['x1', 'x2'])
adf

  x1  x2
0  A   1
1  B   2
2  C   3

In [19]:
bdf = pd.DataFrame(
    [['A',True],
     ['B',False],
     ['D',True]],
    columns=['x1', 'x3'])
bdf

  x1     x3
0  A   True
1  B  False
2  D   True

### Inner Join

The simplest type of join is the inner join. An inner join matches pairs of observations whenever their keys are equal:

In [20]:
pd.merge(adf, bdf, how='inner', on='x1')

  x1  x2     x3
0  A   1   True
1  B   2  False

In [21]:
# You can do this as well.
adf.merge(bdf, how='inner', on='x1')

  x1  x2     x3
0  A   1   True
1  B   2  False

### Outer Joins

- A left join keeps all observations in adf.
- A right join keeps all observations in bdf.
- A full join keeps all observations in adf and bdf.

In [22]:
# Left join
pd.merge(adf, bdf, how='left', on='x1')

  x1  x2     x3
0  A   1   True
1  B   2  False
2  C   3    NaN

In [23]:
# Right join
pd.merge(adf, bdf, how='right', on='x1')

  x1   x2     x3
0  A  1.0   True
1  B  2.0  False
2  D  NaN   True

In [24]:
# Full outer join
pd.merge(adf, bdf, how='outer', on='x1')

  x1   x2     x3
0  A  1.0   True
1  B  2.0  False
2  C  3.0    NaN
3  D  NaN   True

### Filter Joins

In [25]:
# All rows in adf that have a match in bdf
adf[adf.x1.isin(bdf.x1)]

  x1  x2
0  A   1
1  B   2

In [26]:
# All rows in adf that do not have a match in bdf
adf[~adf.x1.isin(bdf.x1)]

  x1  x2
2  C   3

## Set-like Operations

In Pandas, the `merge()` method can also be used for set-like operations, such as `union`, `intersection`, and `set-difference`. All these operations work with a complete row, comparing the values of every variable.

Take these as examples:

In [27]:
xdf = pd.DataFrame(
    [['A',1],
     ['B',2],
     ['C',3]],
    columns=['x1', 'x2'])
xdf

  x1  x2
0  A   1
1  B   2
2  C   3

In [28]:
ydf = pd.DataFrame(
    [['B',2],
     ['C',3],
     ['D',4]],
    columns=['x1', 'x2'])
ydf

  x1  x2
0  B   2
1  C   3
2  D   4

In [29]:
# Union: Rows that appear in either or both xdf and ydf
pd.merge(xdf, ydf, how='outer')

  x1  x2
0  A   1
1  B   2
2  C   3
3  D   4

In [30]:
# Intersection: Rows that appear in both xdf and ydf
pd.merge(xdf, ydf)

  x1  x2
0  B   2
1  C   3

In [31]:
# Difference: Rows that appear in xdf but not in ydf
pd.merge(xdf, ydf, how='outer', indicator=True).query('_merge == "left_only"').drop(columns=['_merge'])

  x1  x2
0  A   1

## Appending Rows or Columns to Dataframe

When working with multiple dataframes, we often need to combine them by rows or by columns. This is when we need to use the `concat()` method.

In [32]:
# xdf and ydf have the same variables (columns)
# Append rows in ydf to xdf
pd.concat([xdf, ydf])

  x1  x2
0  A   1
1  B   2
2  C   3
0  B   2
1  C   3
2  D   4

In [33]:
# Create a new dataframe zdf
zdf = pd.DataFrame(
    [[True, 4],
     [False, 5],
     [False, 6]],
    columns=['x3','x4'])
zdf

      x3  x4
0   True   4
1  False   5
2  False   6

In [34]:
# xdf and zdf contain different variables of the same data instances in the same order.
# Append the columns of zdf to xdf
pd.concat([xdf, zdf], axis=1)

  x1  x2     x3  x4
0  A   1   True   4
1  B   2  False   5
2  C   3  False   6

## Examples

Let's use merge() on our flights data. For these examples, we’ll make it easier to see what’s going on by creating a narrower dataframe:

In [35]:
# Create a smaller dataframe
flights2 = flights[['year','month', 'day', 'hour', 'origin', 'dest', 'tailnum', 'carrier']]
flights2

        year  month  day  hour origin dest tailnum carrier
0       2013      1    1     5    EWR  IAH  N14228      UA
1       2013      1    1     5    LGA  IAH  N24211      UA
2       2013      1    1     5    JFK  MIA  N619AA      AA
3       2013      1    1     5    JFK  BQN  N804JB      B6
4       2013      1    1     6    LGA  ATL  N668DN      DL
...      ...    ...  ...   ...    ...  ...     ...     ...
336771  2013      9   30    14    JFK  DCA     NaN      9E
336772  2013      9   30    22    LGA  SYR     NaN      9E
336773  2013      9   30    12    LGA  BNA  N535MQ      MQ
336774  2013      9   30    11    LGA  CLE  N511MQ      MQ
336775  2013      9   30     8    LGA  RDU  N839MQ      MQ

[336776 rows x 8 columns]

Imagine you want to add the full airline name to the ``flights2`` data. You can combine the ``airlines`` and ``flights2`` data frames with a left join:

In [36]:
pd.merge(flights2, airlines, how='left', on='carrier')

,year,month,day,hour,origin,dest,tailnum,carrier,name
0,2013,1,1,5,EWR,IAH,N14228,UA,United Air Lines Inc.
1,2013,1,1,5,LGA,IAH,N24211,UA,United Air Lines Inc.
2,2013,1,1,5,JFK,MIA,N619AA,AA,American Airlines Inc.
3,2013,1,1,5,JFK,BQN,N804JB,B6,JetBlue Airways
4,2013,1,1,6,LGA,ATL,N668DN,DL,Delta Air Lines Inc.
...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,14,JFK,DCA,NaN,9E,Endeavor Air Inc.
336772,2013,9,30,22,LGA,SYR,NaN,9E,Endeavor Air Inc.
336773,2013,9,30,12,LGA,BNA,N535MQ,MQ,Envoy Air
336774,2013,9,30,11,LGA,CLE,N511MQ,MQ,Envoy Air
336775,2013,9,30,8,LGA,RDU,N839MQ,MQ,Envoy Air

In [37]:
# This gives you the same results
flights2.merge(airlines, how='left', on='carrier')

,year,month,day,hour,origin,dest,tailnum,carrier,name
0,2013,1,1,5,EWR,IAH,N14228,UA,United Air Lines Inc.
1,2013,1,1,5,LGA,IAH,N24211,UA,United Air Lines Inc.
2,2013,1,1,5,JFK,MIA,N619AA,AA,American Airlines Inc.
3,2013,1,1,5,JFK,BQN,N804JB,B6,JetBlue Airways
4,2013,1,1,6,LGA,ATL,N668DN,DL,Delta Air Lines Inc.
...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,14,JFK,DCA,NaN,9E,Endeavor Air Inc.
336772,2013,9,30,22,LGA,SYR,NaN,9E,Endeavor Air Inc.
336773,2013,9,30,12,LGA,BNA,N535MQ,MQ,Envoy Air
336774,2013,9,30,11,LGA,CLE,N511MQ,MQ,Envoy Air
336775,2013,9,30,8,LGA,RDU,N839MQ,MQ,Envoy Air

Sometimes, we need to join on multiple columns.

In [38]:
# For each flight, show the weather of the day as well
pd.merge(flights2, weather, how='left', on=["year", "month", "day", "hour", "origin"])

,year,month,day,hour,origin,dest,tailnum,carrier,temp,dewp,humid,wind_dir,wind_speed,wind_gust,precip,pressure,visib,time_hour
0,2013,1,1,5,EWR,IAH,N14228,UA,39.02,28.04,64.43,260.0,12.65858,NaN,0.0,1011.9,10.0,2013-01-01T10:00:00Z
1,2013,1,1,5,LGA,IAH,N24211,UA,39.92,24.98,54.81,250.0,14.96014,21.86482,0.0,1011.4,10.0,2013-01-01T10:00:00Z
2,2013,1,1,5,JFK,MIA,N619AA,AA,39.02,26.96,61.63,260.0,14.96014,NaN,0.0,1012.1,10.0,2013-01-01T10:00:00Z
3,2013,1,1,5,JFK,BQN,N804JB,B6,39.02,26.96,61.63,260.0,14.96014,NaN,0.0,1012.1,10.0,2013-01-01T10:00:00Z
4,2013,1,1,6,LGA,ATL,N668DN,DL,39.92,24.98,54.81,260.0,16.11092,23.01560,0.0,1011.7,10.0,2013-01-01T11:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,14,JFK,DCA,NaN,9E,68.00,55.04,63.21,190.0,11.50780,NaN,0.0,1016.6,10.0,2013-09-30T18:00:00Z
336772,2013,9,30,22,LGA,SYR,NaN,9E,64.94,53.06,65.37,200.0,6.90468,NaN,0.0,1015.8,10.0,2013-10-01T02:00:00Z
336773,2013,9,30,12,LGA,BNA,N535MQ,MQ,69.08,48.02,46.99,70.0,5.75390,NaN,0.0,1016.7,10.0,2013-09-30T16:00:00Z
336774,2013,9,30,11,LGA,CLE,N511MQ,MQ,66.92,48.92,52.35,70.0,8.05546,NaN,0.0,1017.5,10.0,2013-09-30T15:00:00Z
336775,2013,9,30,8,LGA,RDU,N839MQ,MQ,60.98,51.08,69.86,NaN,5.75390,NaN,0.0,1018.6,10.0,2013-09-30T12:00:00Z

In [39]:
# The default, on = None, uses all matching variables that appear in both tables, the so called 'natural join'.
pd.merge(flights2, weather, how='left')

,year,month,day,hour,origin,dest,tailnum,carrier,temp,dewp,humid,wind_dir,wind_speed,wind_gust,precip,pressure,visib,time_hour
0,2013,1,1,5,EWR,IAH,N14228,UA,39.02,28.04,64.43,260.0,12.65858,NaN,0.0,1011.9,10.0,2013-01-01T10:00:00Z
1,2013,1,1,5,LGA,IAH,N24211,UA,39.92,24.98,54.81,250.0,14.96014,21.86482,0.0,1011.4,10.0,2013-01-01T10:00:00Z
2,2013,1,1,5,JFK,MIA,N619AA,AA,39.02,26.96,61.63,260.0,14.96014,NaN,0.0,1012.1,10.0,2013-01-01T10:00:00Z
3,2013,1,1,5,JFK,BQN,N804JB,B6,39.02,26.96,61.63,260.0,14.96014,NaN,0.0,1012.1,10.0,2013-01-01T10:00:00Z
4,2013,1,1,6,LGA,ATL,N668DN,DL,39.92,24.98,54.81,260.0,16.11092,23.01560,0.0,1011.7,10.0,2013-01-01T11:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,14,JFK,DCA,NaN,9E,68.00,55.04,63.21,190.0,11.50780,NaN,0.0,1016.6,10.0,2013-09-30T18:00:00Z
336772,2013,9,30,22,LGA,SYR,NaN,9E,64.94,53.06,65.37,200.0,6.90468,NaN,0.0,1015.8,10.0,2013-10-01T02:00:00Z
336773,2013,9,30,12,LGA,BNA,N535MQ,MQ,69.08,48.02,46.99,70.0,5.75390,NaN,0.0,1016.7,10.0,2013-09-30T16:00:00Z
336774,2013,9,30,11,LGA,CLE,N511MQ,MQ,66.92,48.92,52.35,70.0,8.05546,NaN,0.0,1017.5,10.0,2013-09-30T15:00:00Z
336775,2013,9,30,8,LGA,RDU,N839MQ,MQ,60.98,51.08,69.86,NaN,5.75390,NaN,0.0,1018.6,10.0,2013-09-30T12:00:00Z

Sometimes, the column names from the two dataframes may not match. Then, you need to explicitly specify the columns from each side.

In [40]:
# We want to combine the flights data with the airports data (key: 'faa').
# For origin:
pd.merge(flights2, airports, how='left', left_on='origin', right_on='faa')

,year,month,day,hour,origin,dest,tailnum,carrier,faa,name,lat,lon,alt,tz,dst,tzone
0,2013,1,1,5,EWR,IAH,N14228,UA,EWR,Newark Liberty Intl,40.692500,-74.168667,18,-5,A,America/New_York
1,2013,1,1,5,LGA,IAH,N24211,UA,LGA,La Guardia,40.777245,-73.872608,22,-5,A,America/New_York
2,2013,1,1,5,JFK,MIA,N619AA,AA,JFK,John F Kennedy Intl,40.639751,-73.778925,13,-5,A,America/New_York
3,2013,1,1,5,JFK,BQN,N804JB,B6,JFK,John F Kennedy Intl,40.639751,-73.778925,13,-5,A,America/New_York
4,2013,1,1,6,LGA,ATL,N668DN,DL,LGA,La Guardia,40.777245,-73.872608,22,-5,A,America/New_York
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,14,JFK,DCA,NaN,9E,JFK,John F Kennedy Intl,40.639751,-73.778925,13,-5,A,America/New_York
336772,2013,9,30,22,LGA,SYR,NaN,9E,LGA,La Guardia,40.777245,-73.872608,22,-5,A,America/New_York
336773,2013,9,30,12,LGA,BNA,N535MQ,MQ,LGA,La Guardia,40.777245,-73.872608,22,-5,A,America/New_York
336774,2013,9,30,11,LGA,CLE,N511MQ,MQ,LGA,La Guardia,40.777245,-73.872608,22,-5,A,America/New_York
336775,2013,9,30,8,LGA,RDU,N839MQ,MQ,LGA,La Guardia,40.777245,-73.872608,22,-5,A,America/New_York

In [41]:
# For destination:
pd.merge(flights2, airports, how='left', left_on='dest', right_on='faa')

,year,month,day,hour,origin,dest,tailnum,carrier,faa,name,lat,lon,alt,tz,dst,tzone
0,2013,1,1,5,EWR,IAH,N14228,UA,IAH,George Bush Intercontinental,29.984433,-95.341442,97.0,-6.0,A,America/Chicago
1,2013,1,1,5,LGA,IAH,N24211,UA,IAH,George Bush Intercontinental,29.984433,-95.341442,97.0,-6.0,A,America/Chicago
2,2013,1,1,5,JFK,MIA,N619AA,AA,MIA,Miami Intl,25.793250,-80.290556,8.0,-5.0,A,America/New_York
3,2013,1,1,5,JFK,BQN,N804JB,B6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2013,1,1,6,LGA,ATL,N668DN,DL,ATL,Hartsfield Jackson Atlanta Intl,33.636719,-84.428067,1026.0,-5.0,A,America/New_York
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,14,JFK,DCA,NaN,9E,DCA,Ronald Reagan Washington Natl,38.852083,-77.037722,15.0,-5.0,A,America/New_York
336772,2013,9,30,22,LGA,SYR,NaN,9E,SYR,Syracuse Hancock Intl,43.111187,-76.106311,421.0,-5.0,A,America/New_York
336773,2013,9,30,12,LGA,BNA,N535MQ,MQ,BNA,Nashville Intl,36.124472,-86.678194,599.0,-6.0,A,America/Chicago
336774,2013,9,30,11,LGA,CLE,N511MQ,MQ,CLE,Cleveland Hopkins Intl,41.411689,-81.849794,791.0,-5.0,A,America/New_York
336775,2013,9,30,8,LGA,RDU,N839MQ,MQ,RDU,Raleigh Durham Intl,35.877639,-78.787472,435.0,-5.0,A,America/New_York

## Exercises

In [57]:
# Compute the average arrival delay by destination,
# then join with the airports dataframe.
flights.groupby('dest').arr_delay.mean().to_frame().merge(airports[['faa','name']], how='left', left_on='dest', right_on='faa')

     arr_delay  faa                               name
0     4.381890  ABQ  Albuquerque International Sunport
1     4.852273  ACK                      Nantucket Mem
2    14.397129  ALB                        Albany Intl
3    -2.500000  ANC         Ted Stevens Anchorage Intl
4    11.300113  ATL    Hartsfield Jackson Atlanta Intl
..         ...  ...                                ...
100   7.408525  TPA                         Tampa Intl
101  33.659864  TUL                         Tulsa Intl
102  12.968421  TVC             Cherry Capital Airport
103  24.069204  TYS                      Mc Ghee Tyson
104   7.465726  XNA               NW Arkansas Regional

[105 rows x 3 columns]

In [62]:
# Add the fullname of the origin and destination airports to flights.
flights.merge(airports, how='left', left_on='origin', right_on='faa').merge(airports, how='left', left_on='dest', right_on='faa')

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,...,average arrival delay_x,faa_y,name_y,lat_y,lon_y,alt_y,tz_y,dst_y,tzone_y,average arrival delay_y
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,...,NaN,IAH,George Bush Intercontinental,29.984433,-95.341442,97.0,-6.0,A,America/Chicago,NaN
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,...,NaN,IAH,George Bush Intercontinental,29.984433,-95.341442,97.0,-6.0,A,America/Chicago,NaN
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,...,NaN,MIA,Miami Intl,25.793250,-80.290556,8.0,-5.0,A,America/New_York,NaN
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,...,NaN,ATL,Hartsfield Jackson Atlanta Intl,33.636719,-84.428067,1026.0,-5.0,A,America/New_York,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,...,NaN,DCA,Ronald Reagan Washington Natl,38.852083,-77.037722,15.0,-5.0,A,America/New_York,NaN
336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,...,NaN,SYR,Syracuse Hancock Intl,43.111187,-76.106311,421.0,-5.0,A,America/New_York,NaN
336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,...,NaN,BNA,Nashville Intl,36.124472,-86.678194,599.0,-6.0,A,America/Chicago,NaN
336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,...,NaN,CLE,Cleveland Hopkins Intl,41.411689,-81.849794,791.0,-5.0,A,America/New_York,NaN
336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,...,NaN,RDU,Raleigh Durham Intl,35.877639,-78.787472,435.0,-5.0,A,America/New_York,NaN

In [59]:
# What weather conditions make it more likely to cause a departure delay?
flights.merge(weather, how='left', on=["year", "month", "day", "hour", "origin"])

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,...,temp,dewp,humid,wind_dir,wind_speed,wind_gust,precip,pressure,visib,time_hour_y
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,...,39.02,28.04,64.43,260.0,12.65858,NaN,0.0,1011.9,10.0,2013-01-01T10:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,...,39.92,24.98,54.81,250.0,14.96014,21.86482,0.0,1011.4,10.0,2013-01-01T10:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,...,39.02,26.96,61.63,260.0,14.96014,NaN,0.0,1012.1,10.0,2013-01-01T10:00:00Z
3,2013,1,1,544.0,545,-1.0,1004.0,1022,-18.0,B6,...,39.02,26.96,61.63,260.0,14.96014,NaN,0.0,1012.1,10.0,2013-01-01T10:00:00Z
4,2013,1,1,554.0,600,-6.0,812.0,837,-25.0,DL,...,39.92,24.98,54.81,260.0,16.11092,23.01560,0.0,1011.7,10.0,2013-01-01T11:00:00Z
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336771,2013,9,30,NaN,1455,NaN,NaN,1634,NaN,9E,...,68.00,55.04,63.21,190.0,11.50780,NaN,0.0,1016.6,10.0,2013-09-30T18:00:00Z
336772,2013,9,30,NaN,2200,NaN,NaN,2312,NaN,9E,...,64.94,53.06,65.37,200.0,6.90468,NaN,0.0,1015.8,10.0,2013-10-01T02:00:00Z
336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,...,69.08,48.02,46.99,70.0,5.75390,NaN,0.0,1016.7,10.0,2013-09-30T16:00:00Z
336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,...,66.92,48.92,52.35,70.0,8.05546,NaN,0.0,1017.5,10.0,2013-09-30T15:00:00Z
336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,...,60.98,51.08,69.86,NaN,5.75390,NaN,0.0,1018.6,10.0,2013-09-30T12:00:00Z