<a href="https://colab.research.google.com/github/ianelgar40/IansMIS433/blob/main/Copy_of_assignment_IMDB_tidy_data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Assignment - Analyzing the IMDB Top 1000 Movies

In the next few assignments, you will be working with this data set of IMDB top 1000 movies.

Source: https://www.kaggle.com/harshitshankhdhar/imdb-dataset-of-top-1000-movies-and-tv-shows

In [1]:
import pandas as pd
import numpy as np

In [2]:
# Read the data file "imdb_top_1000.csv" to a dataframe named "imdb"
imdb = pd.read_csv('https://raw.githubusercontent.com/jiexunli-wwu/mis433/refs/heads/main/data/imdb_top_1000.csv', header=0)
imdb.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [3]:
# Number of rows?
# Number of columns?
imdb.shape

(1000, 16)

In [4]:
# Describe the dataframe using the info() method.
imdb.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   object
 1   Series_Title   1000 non-null   object
 2   Released_Year  1000 non-null   object
 3   Certificate    899 non-null    object
 4   Runtime        1000 non-null   object
 5   Genre          1000 non-null   object
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   object
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   object
 10  Star1          1000 non-null   object
 11  Star2          1000 non-null   object
 12  Star3          1000 non-null   object
 13  Star4          1000 non-null   object
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    object
dtypes: float64(2), int64(1), object(13)
memory usage: 125.1+ KB

In [5]:
# Use describe() to summarize the descriptive statistics of *all* columns
imdb.describe(include='all')

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
count,1000,1000,1000,899,1000,1000,1000.000000,1000,843.000000,1000,1000,1000,1000,1000,1.000000e+03,831
unique,1000,999,100,16,140,202,NaN,1000,NaN,548,660,841,891,939,NaN,823
top,https://m.media-amazon.com/images/M/MV5BMTY5OD...,Drishyam,2014,U,100 min,Drama,NaN,A man in London tries to help a counter-espion...,NaN,Alfred Hitchcock,Tom Hanks,Emma Watson,Rupert Grint,Michael Caine,NaN,"4,360,000"
freq,1,2,32,234,23,85,NaN,1,NaN,14,12,7,5,4,NaN,5
mean,NaN,NaN,NaN,NaN,NaN,NaN,7.949300,NaN,77.971530,NaN,NaN,NaN,NaN,NaN,2.736929e+05,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,0.275491,NaN,12.376099,NaN,NaN,NaN,NaN,NaN,3.273727e+05,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,7.600000,NaN,28.000000,NaN,NaN,NaN,NaN,NaN,2.508800e+04,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,7.700000,NaN,70.000000,NaN,NaN,NaN,NaN,NaN,5.552625e+04,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,7.900000,NaN,79.000000,NaN,NaN,NaN,NaN,NaN,1.385485e+05,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,8.100000,NaN,87.000000,NaN,NaN,NaN,NaN,NaN,3.741612e+05,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,9.300000,NaN,100.000000,NaN,NaN,NaN,NaN,NaN,2.343110e+06,NaN

In [6]:
# List all the column names:
imdb.columns

Index(['Poster_Link', 'Series_Title', 'Released_Year', 'Certificate',
       'Runtime', 'Genre', 'IMDB_Rating', 'Overview', 'Meta_score', 'Director',
       'Star1', 'Star2', 'Star3', 'Star4', 'No_of_Votes', 'Gross'],
      dtype='object')

## Part 1: Data Manipulation

In [7]:
# In this dataset, there is a movie with an error in "Released_Year". (Hint: Released_Year should be a 4-digit integer.)
# Find this movie.
imdb[imdb['Released_Year'].str.isdigit()==False]

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
966,https://m.media-amazon.com/images/M/MV5BNjEzYj...,Apollo 13,PG,U,140 min,"Adventure, Drama, History",7.6,NASA must devise a strategy to return Apollo 1...,77.0,Ron Howard,Tom Hanks,Bill Paxton,Kevin Bacon,Gary Sinise,269197,"173,837,933"

In [8]:
imdb['Released_Year'].unique()

array(['1994', '1972', '2008', '1974', '1957', '2003', '1993', '2010',
       '1999', '2001', '1966', '2002', '1990', '1980', '1975', '2020',
       '2019', '2014', '1998', '1997', '1995', '1991', '1977', '1962',
       '1954', '1946', '2011', '2006', '2000', '1988', '1985', '1968',
       '1960', '1942', '1936', '1931', '2018', '2017', '2016', '2012',
       '2009', '2007', '1984', '1981', '1979', '1971', '1963', '1964',
       '1950', '1940', '2013', '2005', '2004', '1992', '1987', '1986',
       '1983', '1976', '1973', '1965', '1959', '1958', '1952', '1948',
       '1944', '1941', '1927', '1921', '2015', '1996', '1989', '1978',
       '1961', '1955', '1953', '1925', '1924', '1982', '1967', '1951',
       '1949', '1939', '1937', '1934', '1928', '1926', '1920', '1970',
       '1969', '1956', '1947', '1945', '1930', '1938', '1935', '1933',
       '1932', '1922', '1943', 'PG'], dtype=object)

In [9]:
# Correct the values for the corresponding columns ("Release_Year" and "Certificate").
# You may want to look up this movie on www.imdb.com.
# Hint: You can set value for a particular set by: loc[row_name, column_name] = new_value
imdb.loc[966,'Released_Year'] = 1995
imdb.loc[966,'Certificate'] = 'PG'
imdb.loc[966]

Poster_Link      https://m.media-amazon.com/images/M/MV5BNjEzYj...
Series_Title                                             Apollo 13
Released_Year                                                 1995
Certificate                                                     PG
Runtime                                                    140 min
Genre                                    Adventure, Drama, History
IMDB_Rating                                                    7.6
Overview         NASA must devise a strategy to return Apollo 1...
Meta_score                                                    77.0
Director                                                Ron Howard
Star1                                                    Tom Hanks
Star2                                                  Bill Paxton
Star3                                                  Kevin Bacon
Star4                                                  Gary Sinise
No_of_Votes                                                 269197
Gross                                                  173,837,933
Name: 966, dtype: object

In [10]:
# Change "Released_Year" from string to int
imdb['Released_Year'] = imdb['Released_Year'].apply(int)
imdb['Released_Year'].dtype

dtype('int64')

In [11]:
# Create a new dataframe called "stars" including the following columns:
# Series_Title, Released_Year, Star1, Star2, Star3, Star4
stars = imdb[['Series_Title', 'Released_Year', 'Star1', 'Star2', 'Star3', 'Star4']]
stars

,Series_Title,Released_Year,Star1,Star2,Star3,Star4
0,The Shawshank Redemption,1994,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler
1,The Godfather,1972,Marlon Brando,Al Pacino,James Caan,Diane Keaton
2,The Dark Knight,2008,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine
3,The Godfather: Part II,1974,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton
4,12 Angry Men,1957,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler
...,...,...,...,...,...,...
995,Breakfast at Tiffany's,1961,Audrey Hepburn,George Peppard,Patricia Neal,Buddy Ebsen
996,Giant,1956,Elizabeth Taylor,Rock Hudson,James Dean,Carroll Baker
997,From Here to Eternity,1953,Burt Lancaster,Montgomery Clift,Deborah Kerr,Donna Reed
998,Lifeboat,1944,Tallulah Bankhead,John Hodiak,Walter Slezak,William Bendix
999,The 39 Steps,1935,Robert Donat,Madeleine Carroll,Lucie Mannheim,Godfrey Tearle

In [12]:
# Create a new dataframe called "genres" including the following columns:
# Series_Title, Released_Year, Genre.
genres = imdb[['Series_Title', 'Released_Year', 'Genre']]
genres

                 Series_Title  Released_Year                     Genre
0    The Shawshank Redemption           1994                     Drama
1               The Godfather           1972              Crime, Drama
2             The Dark Knight           2008      Action, Crime, Drama
3      The Godfather: Part II           1974              Crime, Drama
4                12 Angry Men           1957              Crime, Drama
..                        ...            ...                       ...
995    Breakfast at Tiffany's           1961    Comedy, Drama, Romance
996                     Giant           1956            Drama, Western
997     From Here to Eternity           1953       Drama, Romance, War
998                  Lifeboat           1944                Drama, War
999              The 39 Steps           1935  Crime, Mystery, Thriller

[1000 rows x 3 columns]

In [13]:
# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their title, released year, Certificate, and gross.
# Sort them in descending order of "Gross"
(
    imdb[(imdb.Released_Year>=2010) & (imdb.IMDB_Rating>=8.5)]
    [['Series_Title','Released_Year','Certificate','Gross']]
    .sort_values('Gross', ascending=False)
)

        Series_Title  Released_Year Certificate        Gross
19      Gisaengchung           2019           A   53,367,844
33             Joker           2019           A  335,451,311
8          Inception           2010          UA  292,576,195
21      Interstellar           2014          UA  188,020,017
35  The Intouchables           2011          UA   13,182,281
34          Whiplash           2014           A   13,092,000
18          Hamilton           2020       PG-13          NaN
20   Soorarai Pottru           2020           U          NaN

In [ ]:
# Does the sorting result look right to you? What's the problem?

# Answer: Gross is a string type.

In [14]:
# Resolve this problem of "Gross" and convert its data type to float
# Hint: You may find this webpage useful:
# https://stackoverflow.com/questions/28986489/how-to-replace-text-in-a-column-of-a-pandas-dataframe

imdb['Gross'] = imdb['Gross'].apply(str).str.replace(',','').apply(float)
imdb['Gross']

0       28341469.0
1      134966411.0
2      534858444.0
3       57300000.0
4        4360000.0
          ...
995            NaN
996            NaN
997     30500000.0
998            NaN
999            NaN
Name: Gross, Length: 1000, dtype: float64

In [15]:
# Next, redo the sorting on Gross

# Select all movies released after (>=) 2010 and with IMDB_Rating>=8.5
# Show their title, released year, Certificate, and gross.
# Sort them in descending order of "Gross"
(
    imdb[(imdb.Released_Year>=2010) & (imdb.IMDB_Rating>=8.5)]
    [['Series_Title','Released_Year','Certificate','Gross']]
    .sort_values('Gross', ascending=False)
)

        Series_Title  Released_Year Certificate        Gross
33             Joker           2019           A  335451311.0
8          Inception           2010          UA  292576195.0
21      Interstellar           2014          UA  188020017.0
19      Gisaengchung           2019           A   53367844.0
35  The Intouchables           2011          UA   13182281.0
34          Whiplash           2014           A   13092000.0
18          Hamilton           2020       PG-13          NaN
20   Soorarai Pottru           2020           U          NaN

In [16]:
# Add a new column "Runtime_min" by removing the string ' min" in "Runtime"
# Set its data type as int

imdb['Runtime_min'] = imdb['Runtime'].str[:-4].astype(int)
imdb['Runtime_min']

0      142
1      175
2      152
3      202
4       96
      ...
995    115
996    201
997    118
998     97
999     86
Name: Runtime_min, Length: 1000, dtype: int64

In [17]:
# Add a new column "Decade" with values as 1980, 1990, 2000, 2010, 2020, etc.
imdb['Decade'] = imdb['Released_Year'] // 10 * 10
imdb['Decade']

0      1990
1      1970
2      2000
3      1970
4      1950
       ...
995    1960
996    1950
997    1950
998    1940
999    1930
Name: Decade, Length: 1000, dtype: int64

## Part 2: Data Summarization
Done!

## Part 3: Data Visualization
Done!

## Part 4: Tidy Data

After running all cells above, you should have three dataframes:
- **imdb**
- **stars**
- **genres**

Now, let's take a quick look at the three dataframes.

In [18]:
print(imdb.columns)
imdb.head()

Index(['Poster_Link', 'Series_Title', 'Released_Year', 'Certificate',
       'Runtime', 'Genre', 'IMDB_Rating', 'Overview', 'Meta_score', 'Director',
       'Star1', 'Star2', 'Star3', 'Star4', 'No_of_Votes', 'Gross',
       'Runtime_min', 'Decade'],
      dtype='object')

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross,Runtime_min,Decade
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,28341469.0,142,1990
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,134966411.0,175,1970
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,534858444.0,152,2000
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,57300000.0,202,1970
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,4360000.0,96,1950

In [19]:
print(stars.columns)
stars.head()

Index(['Series_Title', 'Released_Year', 'Star1', 'Star2', 'Star3', 'Star4'], dtype='object')

,Series_Title,Released_Year,Star1,Star2,Star3,Star4
0,The Shawshank Redemption,1994,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler
1,The Godfather,1972,Marlon Brando,Al Pacino,James Caan,Diane Keaton
2,The Dark Knight,2008,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine
3,The Godfather: Part II,1974,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton
4,12 Angry Men,1957,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler

In [20]:
print(genres.columns)
genres.head()

Index(['Series_Title', 'Released_Year', 'Genre'], dtype='object')

               Series_Title  Released_Year                 Genre
0  The Shawshank Redemption           1994                 Drama
1             The Godfather           1972          Crime, Drama
2           The Dark Knight           2008  Action, Crime, Drama
3    The Godfather: Part II           1974          Crime, Drama
4              12 Angry Men           1957          Crime, Drama

Follow the instructions below and write your code to answer the questions:

To better understand the advantages of tidy data, you will first use the "un-tidy" dataframes alone to answer the next few questions:

In [21]:
# In dataframe "stars", find all movies that star "Morgan Freeman".
# Hint: he could be Star1, Star2, Star3, or Star4.
stars[(stars['Star1']=='Morgan Freeman') | (stars['Star2']=='Morgan Freeman') | (stars['Star3']=='Morgan Freeman') | (stars['Star4']=='Morgan Freeman')]

,Series_Title,Released_Year,Star1,Star2,Star3,Star4
0,The Shawshank Redemption,1994,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler
27,Se7en,1995,Morgan Freeman,Brad Pitt,Kevin Spacey,Andrew Kevin Walker
167,Unforgiven,1992,Clint Eastwood,Gene Hackman,Morgan Freeman,Richard Harris
234,Million Dollar Baby,2004,Hilary Swank,Clint Eastwood,Morgan Freeman,Jay Baruchel
673,Glory,1989,Matthew Broderick,Denzel Washington,Cary Elwes,Morgan Freeman
768,Lucky Number Slevin,2006,Josh Hartnett,Ben Kingsley,Morgan Freeman,Lucy Liu
922,Gone Baby Gone,2007,Morgan Freeman,Ed Harris,Casey Affleck,Michelle Monaghan

In [22]:
# In dataframe 'stars', who appeared in Star2 the most times? List the top five actors.
stars.Star2.value_counts().head()

Star2
Emma Watson     7
Matt Damon      5
Ian McKellen    4
Brad Pitt       4
Kate Winslet    4
Name: count, dtype: int64

In [23]:
# In dataframe 'imdb', find all comedies and list Series_Title, Released_Year, Director, and IMDB_Rating
# Sort them by Released_Year in descending order.
# Hint: use .str.contains(...)
imdb[imdb['Genre'].str.contains('Comedy')][['Series_Title','Released_Year','Director','IMDB_Rating']].sort_values('Released_Year', ascending=False)

      Series_Title  Released_Year           Director  IMDB_Rating
205           Soul           2020        Pete Docter          8.1
464    Dil Bechara           2020     Mukesh Chhabra          7.9
613           Druk           2020  Thomas Vinterberg          7.8
19    Gisaengchung           2019       Bong Joon Ho          8.6
128     Chhichhore           2019      Nitesh Tiwari          8.2
..             ...            ...                ...          ...
318     The Circus           1928    Charles Chaplin          8.1
320    The General           1926     Clyde Bruckman          8.1
193  The Gold Rush           1925    Charles Chaplin          8.2
194   Sherlock Jr.           1924      Buster Keaton          8.2
127        The Kid           1921    Charles Chaplin          8.3

[233 rows x 4 columns]

In [24]:
# In dataframe 'imdb', find all values in the Genre column and the number of occurrences for each value.
# Hint: use value_counts()
imdb.Genre.value_counts()

Genre
Drama                        85
Drama, Romance               37
Comedy, Drama                35
Comedy, Drama, Romance       31
Action, Crime, Drama         30
                             ..
Action, Adventure, Family     1
Action, Crime, Mystery        1
Animation, Drama, Romance     1
Drama, War, Western           1
Adventure, Comedy, War        1
Name: count, Length: 202, dtype: int64

### Tidying the data

Next, you will further tidy the two dataframes **stars** and **genres**.

Let's start with **stars**.

In [25]:
# Transform the dataframe "stars" to a new dataframe named "stars_long" with the following four columns:
# Series_Title, Released_Year, StarNo (e.g., Star1, Star2, ...), StarName
# Hint: use melt()
stars_long = stars.melt(id_vars=['Series_Title','Released_Year'], value_vars=['Star1','Star2','Star3','Star4'], var_name='StarNo', value_name='StarName')
stars_long

                  Series_Title  Released_Year StarNo        StarName
0     The Shawshank Redemption           1994  Star1     Tim Robbins
1                The Godfather           1972  Star1   Marlon Brando
2              The Dark Knight           2008  Star1  Christian Bale
3       The Godfather: Part II           1974  Star1       Al Pacino
4                 12 Angry Men           1957  Star1     Henry Fonda
...                        ...            ...    ...             ...
3995    Breakfast at Tiffany's           1961  Star4     Buddy Ebsen
3996                     Giant           1956  Star4   Carroll Baker
3997     From Here to Eternity           1953  Star4      Donna Reed
3998                  Lifeboat           1944  Star4  William Bendix
3999              The 39 Steps           1935  Star4  Godfrey Tearle

[4000 rows x 4 columns]

In [26]:
# Can you transform dataframe 'stars_long' back to its original shape?
# Hint: use pivot()
stars_long.pivot(index=['Series_Title','Released_Year'], columns='StarNo', values='StarName')

,StarNo,Star1,Star2,Star3,Star4
Series_Title,Released_Year,,,,
(500) Days of Summer,2009,Zooey Deschanel,Joseph Gordon-Levitt,Geoffrey Arend,Chloë Grace Moretz
12 Angry Men,1957,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler
12 Years a Slave,2013,Chiwetel Ejiofor,Michael Kenneth Williams,Michael Fassbender,Brad Pitt
1917,2019,Dean-Charles Chapman,George MacKay,Daniel Mays,Colin Firth
2001: A Space Odyssey,1968,Keir Dullea,Gary Lockwood,William Sylvester,Daniel Richter
...,...,...,...,...,...
Zootopia,2016,Rich Moore,Jared Bush,Ginnifer Goodwin,Jason Bateman
Zulu,1964,Stanley Baker,Jack Hawkins,Ulla Jacobsson,James Booth
Zwartboek,2006,Carice van Houten,Sebastian Koch,Thom Hoffman,Halina Reijn
À bout de souffle,1960,Jean-Paul Belmondo,Jean Seberg,Daniel Boulanger,Henri-Jacques Huet
Ôkami kodomo no Ame to Yuki,2012,Aoi Miyazaki,Takao Osawa,Haru Kuroki,Yukito Nishii

In [27]:
# In dataframe "stars_long", find all movies that star "Morgan Freeman".
stars_long[stars_long['StarName']=='Morgan Freeman']

                  Series_Title  Released_Year StarNo        StarName
27                       Se7en           1995  Star1  Morgan Freeman
922             Gone Baby Gone           2007  Star1  Morgan Freeman
1000  The Shawshank Redemption           1994  Star2  Morgan Freeman
2167                Unforgiven           1992  Star3  Morgan Freeman
2234       Million Dollar Baby           2004  Star3  Morgan Freeman
2768       Lucky Number Slevin           2006  Star3  Morgan Freeman
3673                     Glory           1989  Star4  Morgan Freeman

In [28]:
# Who appeared in Star2 the most times? List the top five actors.
stars_long.loc[stars_long['StarNo']=='Star2']['StarName'].value_counts().head()

StarName
Emma Watson     7
Matt Damon      5
Ian McKellen    4
Brad Pitt       4
Kate Winslet    4
Name: count, dtype: int64

In [29]:
# Who stars in the most movies in this list? List the top 20 actors.
stars_long['StarName'].value_counts().head(20)

StarName
Robert De Niro        17
Tom Hanks             14
Al Pacino             13
Clint Eastwood        12
Brad Pitt             12
Leonardo DiCaprio     11
Matt Damon            11
Christian Bale        11
James Stewart         10
Denzel Washington      9
Johnny Depp            9
Michael Caine          9
Scarlett Johansson     9
Humphrey Bogart        9
Ethan Hawke            9
Harrison Ford          8
Aamir Khan             8
Jake Gyllenhaal        7
Jeff Bridges           7
Bruce Willis           7
Name: count, dtype: int64

In [30]:
# Which movie stars had the highest total gross in this movie list? Show the top 10 actors.
# Hint: Join "stars_long" and "imdb"; then group by StarName
stars_long.merge(imdb, on=['Series_Title','Released_Year']).groupby('StarName')['Gross'].sum().sort_values(ascending=False).head(10).reset_index()

            StarName         Gross
0  Robert Downey Jr.  3.129073e+09
1          Tom Hanks  2.903565e+09
2        Chris Evans  2.339664e+09
3          Joe Russo  2.205039e+09
4       Mark Ruffalo  2.058396e+09
5  Leonardo DiCaprio  2.049297e+09
6       Ian McKellen  1.869869e+09
7   Daniel Radcliffe  1.835901e+09
8       Rupert Grint  1.835901e+09
9         Matt Damon  1.728542e+09

In [35]:
# Find the best director-actor duos
# i.e., director-actor pairs that collaborated in at least five movies,
# sort them in descending order of average IMDB_Rating
# Hint: Join imdb and stars_long; group by ['Director','StarName']
director_actor=imdb.merge(stars_long, on=['Series_Title','Released_Year']).groupby(['Director','StarName'])['IMDB_Rating'].mean().sort_values(ascending=False).reset_index()
director_actor['Average IMDB_Rating'] = director_actor['IMDB_Rating']
director_actor.drop(columns=['IMDB_Rating']).groupby(['Director','StarName']).count().query('Average IMDB_Rating >= 5').sort_values('Average IMDB_Rating', ascending=False)

                  Director           StarName  IMDB_Rating
0           Frank Darabont        Tim Robbins          9.3
1           Frank Darabont         Bob Gunton          9.3
2           Frank Darabont     William Sadler          9.3
3           Frank Darabont     Morgan Freeman          9.3
4     Francis Ford Coppola         James Caan          9.2
...                    ...                ...          ...
3726        Chris Columbus    Macaulay Culkin          7.6
3727        Chris Columbus       Maggie Smith          7.6
3728        Chris Columbus     Richard Harris          7.6
3729        Chris Columbus       Rupert Grint          7.6
3730           Guy Ritchie  Robert Downey Jr.          7.6

[3731 rows x 3 columns]

In [40]:
# Find the best director-actor duos
# i.e., director-actor pairs that collaborated in at least five movies,
# sort them in descending order of average IMDB_Rating
# Hint: Join imdb and stars_long; group by ['Director','StarName']
merged_df = imdb.merge(stars_long, on=['Series_Title', 'Released_Year'])
collaboration_stats = merged_df.groupby(['Director', 'StarName']).agg(
    collaboration_count=('Series_Title', 'size'),
    average_IMDB_Rating=('IMDB_Rating', 'mean')
).reset_index()
best_duos = collaboration_stats[collaboration_stats['collaboration_count'] >= 5]
best_duos = best_duos.sort_values(by='average_IMDB_Rating', ascending=False)

best_duos

,Director,StarName,collaboration_count,average_IMDB_Rating
2600,Peter Jackson,Ian McKellen,5,8.400000
569,Charles Chaplin,Charles Chaplin,6,8.333333
55,Akira Kurosawa,Toshirô Mifune,7,8.242857
2166,Martin Scorsese,Robert De Niro,6,8.183333
54,Akira Kurosawa,Tatsuya Nakadai,5,8.180000
2745,Richard Linklater,Ethan Hawke,5,7.960000
652,Clint Eastwood,Clint Eastwood,5,7.960000
3654,Woody Allen,Woody Allen,5,7.840000
1681,Joel Coen,Ethan Coen,6,7.816667

In [51]:
# Bonus question
# Who did "Amy Adams" co-star with in this movie list?
# Hint: Join stars_long with itself to find pairs of co-stars
imdb.loc[imdb['Star1'] =='Amy Adams'] [['Series_Title','Released_Year', 'Star1', 'Star2', 'Star3', 'Star4']]

,Series_Title,Released_Year,Star1,Star2,Star3,Star4
476,Arrival,2016,Amy Adams,Jeremy Renner,Forest Whitaker,Michael Stuhlbarg

Next, let's reshape the dataframe **genres**, which is a little bit more complicated.

In [52]:
# Step 1: Split the 'Genre' string by ', ' into a list of individual genres and expand them to different columns
genres_split = genres['Genre'].str.split(', ', expand=True)
genres_split

          0        1         2
0     Drama     None      None
1     Crime    Drama      None
2    Action    Crime     Drama
3     Crime    Drama      None
4     Crime    Drama      None
..      ...      ...       ...
995  Comedy    Drama   Romance
996   Drama  Western      None
997   Drama  Romance       War
998   Drama      War      None
999   Crime  Mystery  Thriller

[1000 rows x 3 columns]

In [53]:
# Step 2: Rename the columns as: Genre1, Genre2, Genre3
genres_split.columns = ['Genre1', 'Genre2', 'Genre3']
genres_split

     Genre1   Genre2    Genre3
0     Drama     None      None
1     Crime    Drama      None
2    Action    Crime     Drama
3     Crime    Drama      None
4     Crime    Drama      None
..      ...      ...       ...
995  Comedy    Drama   Romance
996   Drama  Western      None
997   Drama  Romance       War
998   Drama      War      None
999   Crime  Mystery  Thriller

[1000 rows x 3 columns]

In [54]:
# Step 3: Combine ['Series_Title','Released_Year'] in 'genres' and ['Genre1','Genre2','Genre3'] in 'genres_split'.
# Save it to a new dataframe named 'genres_wide'.
# Hint: Use pd.concat(...)
genres_wide = pd.concat([genres[['Series_Title','Released_Year']], genres_split], axis=1)
genres_wide

                 Series_Title  Released_Year  Genre1   Genre2    Genre3
0    The Shawshank Redemption           1994   Drama     None      None
1               The Godfather           1972   Crime    Drama      None
2             The Dark Knight           2008  Action    Crime     Drama
3      The Godfather: Part II           1974   Crime    Drama      None
4                12 Angry Men           1957   Crime    Drama      None
..                        ...            ...     ...      ...       ...
995    Breakfast at Tiffany's           1961  Comedy    Drama   Romance
996                     Giant           1956   Drama  Western      None
997     From Here to Eternity           1953   Drama  Romance       War
998                  Lifeboat           1944   Drama      War      None
999              The 39 Steps           1935   Crime  Mystery  Thriller

[1000 rows x 5 columns]

In [55]:
# Step 4: Transform genres_wide to a new dataframe genres_long with the following four columns:
# Series_Title, Released_Year, GenreNo (e.g., Genre1, Genre2, Genre3), GenreName
# Hint: use melt()
genres_long = genres_wide.melt(id_vars=['Series_Title','Released_Year'], value_vars=['Genre1','Genre2','Genre3'], var_name='GenreNo', value_name='GenreName')
genres_long

                  Series_Title  Released_Year GenreNo GenreName
0     The Shawshank Redemption           1994  Genre1     Drama
1                The Godfather           1972  Genre1     Crime
2              The Dark Knight           2008  Genre1    Action
3       The Godfather: Part II           1974  Genre1     Crime
4                 12 Angry Men           1957  Genre1     Crime
...                        ...            ...     ...       ...
2995    Breakfast at Tiffany's           1961  Genre3   Romance
2996                     Giant           1956  Genre3      None
2997     From Here to Eternity           1953  Genre3       War
2998                  Lifeboat           1944  Genre3      None
2999              The 39 Steps           1935  Genre3  Thriller

[3000 rows x 4 columns]

In [56]:
# How many unique genres (atomic values, e.g., Drama, Comedy, ...) are there?
# How many movies are there for each genre?
genres_long['GenreName'].value_counts()

GenreName
Drama        724
Comedy       233
Crime        209
Adventure    196
Action       189
Thriller     137
Romance      125
Biography    109
Mystery       99
Animation     82
Sci-Fi        67
Fantasy       66
Family        56
History       56
War           51
Music         35
Horror        32
Western       20
Film-Noir     19
Sport         19
Musical       17
Name: count, dtype: int64

In [57]:
# What is the average IMDB rating for each genre?
# Sort the genres in descending order of average IMDB_Rating.
# Hint: join imdb with genres_long; group by GenreName
genres_long.merge(imdb, on=['Series_Title','Released_Year']).groupby('GenreName')['IMDB_Rating'].mean().sort_values(ascending=False).reset_index()

    GenreName  IMDB_Rating
0         War     8.013725
1     Western     8.000000
2   Film-Noir     7.989474
3      Sci-Fi     7.977612
4     Mystery     7.967677
5       Drama     7.959392
6       Crime     7.954545
7     History     7.953571
8   Adventure     7.952041
9      Action     7.948677
10    Musical     7.947059
11  Biography     7.935780
12    Fantasy     7.931818
13  Animation     7.930488
14      Sport     7.926316
15    Romance     7.925600
16      Music     7.914286
17     Family     7.912500
18   Thriller     7.909489
19     Comedy     7.903433
20     Horror     7.887500

In [60]:
# Who is the "King of Comedy" (i.e., the actor who starred in the most comedy movies)?
# Hint: find all comedies in genres_long ; join with stars_long; group by StarName
genres_long[genres_long['GenreName']=='Comedy'].merge(stars_long, on=['Series_Title','Released_Year']).groupby('StarName').count().sort_values('GenreNo', ascending=False).head(2)

                 Series_Title  Released_Year  GenreNo  GenreName  StarNo
StarName
Charles Chaplin             6              6        6          6       6
Bill Murray                 6              6        6          6       6

In [66]:
# Who are the best action stars?
# i.e., the actors who star in at least 5 action movies, sorted by average IMDB rating in descending order
# Hint: You need to join columns from all three dataframes: imdb, stars_long, genres_long


combined_df = genres_long.merge(imdb, on=['Series_Title','Released_Year'])
combined_df = combined_df.merge(stars_long, on=['Series_Title','Released_Year'])

action_star_ratings = combined_df[combined_df['GenreName'] == 'Action']


star_action_stats = action_star_ratings.groupby('StarName').agg(
    num_action_movies=('Series_Title', 'nunique'),
    avg_imdb_rating=('IMDB_Rating', 'mean')
)


best_action_stars = star_action_stats[star_action_stats['num_action_movies'] >= 5]


final_result = best_action_stars.sort_values(by='avg_imdb_rating', ascending=False).reset_index()

final_result

            StarName  num_action_movies  avg_imdb_rating
0      Harrison Ford                  8         8.262500
1     Christian Bale                  6         8.183333
2          Tom Hardy                  5         8.100000
3  Robert Downey Jr.                  6         8.016667

In [72]:
# Create a pivot table to show the number of movies of different genres in different decades.
# Row: GenreName
# Column: Decade
# Hint: https://pandas.pydata.org/docs/reference/api/pandas.pivot_table.html


genres_with_decade = genres_long.merge(imdb[['Series_Title', 'Released_Year', 'Decade']], on=['Series_Title', 'Released_Year'], how='left')


pivot_table = pd.pivot_table(genres_with_decade, values='Series_Title', index='GenreName', columns='Decade', aggfunc='count', fill_value=0).reset_index()
pivot_table

Decade,GenreName,1920,1930,1940,1950,1960,1970,1980,1990,2000,2010,2020
0,Action,2,2,3,2,11,11,20,22,54,62,0
1,Adventure,2,4,3,9,11,14,22,17,52,61,1
2,Animation,0,0,1,0,1,3,8,18,22,28,1
3,Biography,1,0,0,0,9,10,9,15,27,37,1
4,Comedy,5,9,9,8,11,17,26,38,46,61,3
5,Crime,0,4,8,14,9,19,13,45,53,44,0
6,Drama,6,12,25,47,51,49,54,113,182,180,5
7,Family,1,3,3,0,4,5,6,10,16,8,0
8,Fantasy,2,1,2,2,2,4,11,10,21,11,0
9,Film-Noir,0,0,11,8,0,0,0,0,0,0,0
10,History,2,1,1,3,7,4,8,6,11,11,2
11,Horror,2,5,0,2,9,4,2,0,4,4,0
12,Music,0,1,1,1,1,3,2,5,11,10,0
13,Musical,0,2,0,1,2,5,0,0,5,2,0
14,Mystery,1,4,7,7,9,5,4,14,31,17,0
15,Romance,3,5,10,10,7,5,4,24,28,28,1
16,Sci-Fi,1,4,0,2,2,6,12,8,13,19,0
17,Sport,0,0,0,0,1,1,1,3,6,7,0
18,Thriller,1,3,3,9,12,11,9,24,34,30,1
19,War,0,3,5,4,7,7,7,3,8,7,0
20,Western,0,1,1,4,7,3,0,2,0,2,0